manifest:
  remotes:
    - name: finn-e
      url-base: https://github.com/finn-e
  projects:
    # Together with the above defined remote, this refers to a module located at
    # https://github.com/remote-name/repository-name
    - name: zmk-niceview-module
      remote: finn-e